
import { sectionsBase } from "@/config/components.config";
import { getProjectData } from "@/services/api/requests";
import { notFound } from "next/navigation";

import type { Metadata } from "next";
  
export const metadata: Metadata = {
  title: "ShowRoom ",
  description: "Generated by Hoset",
};

export default async function Page({ params }: { params: { slug: string } }) {
  let sectionsToRender: any[] = [];
  let pageColor;
  console.log("Fetching project data for slug:", params.slug);
  try {
    const response = await getProjectData(params.slug);
    console.log("Project data:", response.data);
    pageColor = response.data.data.ColorCode || '#000';

    sectionsToRender = response.data.data.Sections;
  } catch (error) {
    console.error("Error fetching project data:", error);
    notFound();
  }

  // Фоллбек, если секций нет
  if (!sectionsToRender.length) {
    notFound();
  }

  return (
    <>
      {/* Немного колхоза для смены цвета фона страницы, но за-то без синей изоленты) */}
      <style>{`
        body {
          background-color: ${pageColor || '#000'};
        }
      `}</style>

      {sectionsToRender.map((section: any, idx: number) => {
        
        const SectionComp = sectionsBase[section.__component];
        if (!SectionComp) return null;

        return (
          <SectionComp
            key={idx}
            data={section}
          />
        );
      })}
    </>
  );
}