import type { Metadata } from "next";
  
export const metadata: Metadata = {
  title: "ShowRoom ",
  description: "Generated by Hoset",
};

export default async function Page() {
  

  return (
    <>
      Каталог проектов
    </>
  );
}