
import type { Metadata } from "next";
  
export const metadata: Metadata = {
  title: "ShowRoom ",
  description: "Generated by Hoset",
};

const Showroom = () => {
  return (
    <h1>Showroom Page</h1>
  );
}   

export default Showroom;