import type { Metadata } from "next";
import "./globals.css";
import { helveticaNeue, helveticaNeueCyr } from "./fonts";
import Header from "@/components/Header/Header";
import LenisProvider from "@/providers/LenisProvider";
import ViewportHeightProvider from "@/providers/ViewportHeightProvider";
import { GSAPAnimationsProvider } from "@/providers";
import Preloader from "@/components/Preloader/Preloader";



export const metadata: Metadata = {
  title: {
    template: "%s - Hoset",
    default: "Hoset",
  },
  description: "Generated by Hoset",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${helveticaNeue.variable} ${helveticaNeueCyr.variable}`}>
      <body>
        <Preloader />
        <ViewportHeightProvider>
          <LenisProvider classesToExclude={['no-scroll', 'modal', 'popup']}>
            <GSAPAnimationsProvider>
              <Header />
              <main>{children}</main>
            </GSAPAnimationsProvider>
          </LenisProvider>
        </ViewportHeightProvider>
      </body>
    </html>
  );
}
