import type { Metadata } from "next";
import "./globals.css";
import { helveticaNeue, helveticaNeueCyr } from "./fonts";
import Header from "@/components/Header/Header";
import LenisProvider from "@/providers/LenisProvider";



export const metadata: Metadata = {
  title: {
    template: "%s - Hoset",
    default: "Hoset",
  },
  description: "Generated by Hoset",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${helveticaNeue.variable} ${helveticaNeueCyr.variable}`}>
      <body>
        <LenisProvider classesToExclude={['no-scroll', 'modal', 'popup']}>
          <Header />
          <main>{children}</main>
        </LenisProvider>
      </body>
    </html>
  );
}
